### ISSUE TITLE
Scroll to bottom by default

### ISSUE THREAD

**Issue by flovilmart** [rnystrom/Freetime#150] opened 2017-07-16 00:31 UTC
It's quite inconvenient for long threads to manually scroll to bottom, the tableView should scroll to the most recent item in the issue.

**Comment by BasThomas** [comment] 2017-07-16 06:31
Duplicate of #85 :)

**Closed by BasThomas** 2017-07-16 06:31 UTC

**Comment by flovilmart** [comment] 2017-07-16 13:27
Awesome!
